-d D:\A_my_project\Gaowin\Briey_SOC\impl\gwsynthesis\Briey_SOC.vg
-p GW5A-25A-UBGA324-2
-pn GW5A-LV25UG324C2/I1
-cst D:\A_my_project\Gaowin\Briey_SOC\src\Briey_SOC.cst
-cfg D:\A_my_project\Gaowin\Briey_SOC\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
